### ISSUE TITLE
Implementation of roles

### ISSUE THREAD

**Issue by JonasMuehlmann** [JonasMuehlmann/BIB_VPR#112]
Concept:

- Roles are defined per team
- A users roles are included in the _membership_(comma separated `string`?)
- ~Available roles are included in the team(`List<string>` for the class, comma separated `string` for the table?)~

Backend tasks:

- [x] `async Task<bool> Team.AddRole(string role, uint teamId)`
- [x] `async Task<bool> Team.RemoveRole(string role, uint teamId)`
- [x] `async Task<bool> Team.AssignRole(string role, string userId, uint teamId)`
- [x] `async Task<bool> Team.UnassignRloe(string role, string userId, uint teamId)`
- [x] `async Task<List<string>> Team.ListRoles(uint teamId)`
- [x] `async Task<List<string>> Team.GetUsersWithRole(uint teamId, string role)`
- [x] `async Task<List<string>> Team.GetUsersRoles(uint teamId, string userId)`
- [x] Integrate with `MessengerService` and `SignalRService`
- [x] Remove user roles when deleting team roles
- [x] Adjust tests
- [x]  Write new tests
- Adjust other methods    
    - [x] Make team creator admin
- [x] Update production database after merging

Frontend tasks:

- [x] UI controls for managing roles(Add, remove, assign, unassign)

Help wanted on:

- Frontend tasks

**Comment by JayKim94** [comment]
closed by #260
