### ISSUE TITLE
Implement a permission system based on roles

### ISSUE THREAD

**Issue by JonasMuehlmann** [JonasMuehlmann/BIB_VPR#165]
Concept:
- All users with the `admin` role have a tab `permissions` inside of the team settings
- The permissions page lists actions(e.g. Add member, assign roles, etc.) and maps them to a list of roles which are needed to make those actions
- DB schema:
```SQL
CREATE TABLE Team_roles(
Id INT IDENTITY(1,1) PRIMARY KEY,
Role NVARCHAR(40) NOT NULL,
teamId INT FOREIGN KEY REFERENCES [dbo].[Teams](teamId) NOT NULL
);

CREATE TABLE Permissions(
Id INT IDENTITY(1,1) PRIMARY KEY,
permissions NVARCHAR(30) NOT NULL
);

CREATE TABLE Role_permissions(
Id INT IDENTITY(1,1) PRIMARY KEY,
permissionsId INT REFERENCES [dbo].[Permissions](ID) NOT NULL,
team_rolesId INT REFERENCES [dbo].[Team_roles](ID) NOT NULL
);

CREATE TABLE User_roles(
Id INT IDENTITY(1,1) PRIMARY KEY,
userId NVARCHAR(64) FOREIGN KEY REFERENCES  [dbo].[Users](userId) NOT NULL,
team_rolesId INT FOREIGN KEY REFERENCES [dbo].[Team_roles](id) NOT NULL
)
```

Backend Tasks:
- [x] Database implementation
- Basic CRUD functions
    - [x] Grant permission
    - [x] Revoke permission
    - [x] Has Permission?
- [x] Tests
- [x] Grant admin all permissions on team creation
- [x] Integration with `MessengerService` and `SignalR`

Frontend Tasks:
- [x] UI Controls for permission management
- [x] Prevent actions if user does not have correct permissions
- [x] Clear signs of what a user can and cannot do

Depends on:
- #112

**Comment by JayKim94** [comment]
closed by #260
