### ISSUE TITLE
Create emoji picker

### ISSUE THREAD

**Issue by JonasMuehlmann** [JonasMuehlmann/BIB_VPR#232]

**Comment by JonasMuehlmann** [comment]
@JayKim94 I think, you have more work to do than I do. Do you want me to help you out in this a bit by writing a search/ranking algorithm for the emoji picker?

**Comment by JayKim94** [comment]
Yes please, I still have 3-4 more issues to close before this

**Comment by JayKim94** [comment]
> @JonasMuehlmann Yes please, I still have 3-4 more issues to close before this

A method that returns a list of emoji models(unicode, title, category etc.)
and a method that returns emoji model when only title is given(to load reactions for a message)

**Comment by JayKim94** [comment]
closed by #262
