### ISSUE TITLE
Crash when message have two reactions

### ISSUE THREAD

**Issue by robbelDev** [JonasMuehlmann/BIB_VPR#265]
try to fix the crash when somebody reacts 2 times on one message

**Comment by robbelDev** [comment]
@JayKim94 I fixed the bug 🎉but now the like goes up 1 even when I do dislike. Do we need some code to view the other reactions?
![image](https://user-images.githubusercontent.com/71250918/128066285-5fef0daa-aa07-4b52-b54f-c663e8eb96dd.png)
![image](https://user-images.githubusercontent.com/71250918/128066341-aa8444af-cc0c-4886-903b-f98156fcfa7d.png)
![image](https://user-images.githubusercontent.com/71250918/128066311-b77e8c90-1e7a-4c96-8d99-d762a68a7037.png)

**Comment by robbelDev** [comment]
> @JayKim94 I fixed the bug 🎉but now the like goes up 1 even when I do dislike. Do we need some code to view the other reactions?
> ![image](https://user-images.githubusercontent.com/71250918/128066285-5fef0daa-aa07-4b52-b54f-c663e8eb96dd.png)
> ![image](https://user-images.githubusercontent.com/71250918/128066341-aa8444af-cc0c-4886-903b-f98156fcfa7d.png)
> ![image](https://user-images.githubusercontent.com/71250918/128066311-b77e8c90-1e7a-4c96-8d99-d762a68a7037.png)

Ok I am going to fixing this. @JayKim94 or @JonasMuehlmann can you delete my reactions from the Database please.

**Comment by JonasMuehlmann** [comment]
@robbelDev I just deleted all reactions.
