### ISSUE TITLE
Color is not the same for everyone

### ISSUE THREAD

**Issue by RayanMirzaie** [JonasMuehlmann/BIB_VPR#271]
Chat & Notification Icons are sometimes almost hidden when the App starts.

**Comment by JayKim94** [comment]
replacing with static list of colors

[Dark]
Elevation 0 #121212
Elevation 1 #212121
Elevation 2 #313131
Accent #00897B
Accent Muted #00897B88
Link #303F9F

[Light]
Elevation 0 #F9F9F9
Elevation 1 #EFEFEF
Elevation 2 #E1E1E1
Accent #00897B
Accent Muted #00897B88
Link #303F9F

**Comment by JayKim94** [comment]
closed by #287
