### ISSUE TITLE
Teams-Nav-Page

### ISSUE THREAD

**Issue by cjaak** [JonasMuehlmann/BIB_VPR#276]
Teams-Nav-Page shows the Team multiple times after adding members. Once for each member added. Leads to problems with kicking members

**Comment by cjaak** [comment]
https://github.com/JonasMuehlmann/BIB_VPR/fixing-kick-binding

**Comment by cjaak** [comment]
https://github.com/JonasMuehlmann/BIB_VPR/tree/fixing-kick-binding

**Comment by cjaak** [comment]
[https://github.com/JonasMuehlmann/BIB_VPR/tree/fixing-kick-binding](url)

**Comment by JayKim94** [comment]
closed by #288 and #298
